version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///data/chat_database.sqlite
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - app-network

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  app-network:
    driver: bridge